{% set name = "sceptre" %}
{% set version = "3.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sceptre-{{ version }}.tar.gz
  sha256: 2bbe00cca5409475853096a56557d63c3f62cd47c9bc266209961b98f616802e

build:
  number: 0
  noarch: python
  entry_points:
    - sceptre = sceptre.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boto3 >=1.3,<2.0
    - cfn-flip >=1.2.3,<2.0
    - click >=7.0,<9.0
    - colorama >=0.3.9
    - deepdiff >=5.5.0,<6.0
    - jinja2 >=2.8,<3
    - jsonschema >=3.2,<3.3
    - networkx >=2.4,<2.6
    - packaging >=16.8,<17.0
    - python >=3.6
    - pyyaml >=5.1,<6.0
    - sceptre-cmd-resolver >=1.1.3,<2
    - sceptre-file-resolver >=1.0.4,<2
    - six >=1.11.0,<2.0.0

test:
  imports:
    - sceptre
    - sceptre.cli
  commands:
    - pip check
    - sceptre --help
  requires:
    - pip

about:
  home: https://github.com/cloudreach/sceptre
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cloud Provisioning Tool
  description: |
    Sceptre is a tool to drive CloudFormation. It manages the creation,
    update and deletion of stacks while providing meta commands which allow
    users to retrieve information about their stacks.

  doc_url: https://sceptre.cloudreach.com/2.1.5/
  dev_url: https://github.com/Sceptre/sceptre

extra:
  recipe-maintainers:
    - mxr-conda
